apiVersion: batch/v1
kind: Job
metadata:
  name: cms-prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: somkumarva/cms-web:b4205cae1de88b9c094800d0ae8b08338c31d202
          command: ["pnpm", "db:migrate"]
          envFrom:
            - secretRef:
                name: cms-env
