apiVersion: batch/v1
kind: Job
metadata:
  name: cms-prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: somkumarva/cms-web:cae501723bba93e9ad666ced7d7dd2aa9b343f70
          command: ["pnpm", "db:migrate"]
          envFrom:
            - secretRef:
                name: cms-env
