apiVersion: batch/v1
kind: Job
metadata:
  name: cms-prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: somkumarva/cms-web:ee8f4f178279ccb13ea231bb3d4e08bc10bde3c6
          command: ["pnpm", "db:migrate"]
          envFrom:
            - secretRef:
                name: cms-env
