apiVersion: batch/v1
kind: Job
metadata:
  name: cms-prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: somkumarva/cms-web:cb4b62d1ed236d039935dcf957287f189a14cc4c
          command: ["pnpm", "db:migrate"]
          envFrom:
            - secretRef:
                name: cms-env
