apiVersion: batch/v1
kind: Job
metadata:
  name: cms-prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: somkumarva/cms-web:c5dc34000240cd6f46006a70d8891fd97a58f827
          command: ["pnpm", "db:migrate"]
          envFrom:
            - secretRef:
                name: cms-env
