apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-local-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-postgres
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/lib/postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pool-13krotjim-syhw0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-postgres
  resources:
    requests:
      storage: 30Gi
